name: Build Mod

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Make gradlew executable
      run: chmod +x gradlew

    - name: Run Tests
      run: ./gradlew test # 明确运行测试

    - name: Build with Gradle
      run: ./gradlew build -x test # 构建，但不重复运行测试

    - name: Extract mod name (safe version)
      id: mod-info
      run: |
          # 安全地提取模组名称
          if [ -f "gradle.properties" ]; then
            MOD_NAME=$(grep -E "^(mod_name|name|archivesBaseName)=" gradle.properties | head -1 | cut -d'=' -f2 | tr -d '\r' | xargs)
            if [ -z "$MOD_NAME" ]; then
              MOD_NAME="application"
            fi
          else
            MOD_NAME="application"
          fi
          echo "MOD_NAME=$MOD_NAME" >> $GITHUB_OUTPUT
          echo "Using mod name: $MOD_NAME"
      

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.mod-info.outputs.MOD_NAME }}-jar
        path: build/libs/*.jar
        compression-level: 0
        if-no-files-found: error
        retention-days: 5
