name: NeoForge Mod Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build Mod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整提交历史

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant Gradle Permission
        run: chmod +x gradlew

      - name: Build Mod
        run: ./gradlew build --stacktrace --scan  # 启用详细堆栈跟踪

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-mod-1.21.1
          path: |
            build/libs/*-all.jar
            build/libs/*-sources.jar
          retention-days: 7
